### ISSUE TITLE
SQLite Issues when updating from Pouch 3.3.1 to Latest (5.3.1)

### ISSUE THREAD

**Issue by oodavid** [nolanlawson/pouchdb-cordova-hello-world-with-sqlite-plugin#2]
While investigating this issue:

https://github.com/nolanlawson/pouchdb-phonegap-cordova/issues/2

I noticed that this demo worked fine when using the latest version of the cordova-sqlite-storage plugin (against my intuition) - I then updated this to use PouchDB 5.3.1 and saw the error as expected.

Bit new to these projects, so I don't have much more to offer.

**Comment by brody2consult** [comment]
If you guys read README.md carefully you will see that you have to use
_either_ the location or iosDatabaseLocation option. PouchDB has already
supported the location option for a while.

**Comment by oodavid** [comment]
Thanks @brodybits - I didn't connect the two :)
